### ISSUE TITLE
Fail truncating referenced table when using Postgresql

### ISSUE THREAD

**Issue by jefersonralmeida** [mayconbordin/l5-fixtures#8]
When using PostgreSQL, you can't disable the foreign key checks for truncate calls.

I'm preparing a PR to fix that...

**Comment by jefersonralmeida** [comment]
Here is the PR: https://github.com/mayconbordin/l5-fixtures/pull/9

**Comment by mayconbordin** [comment]
Merged. Thanks for the PR!
